Repository softeer5th/Team6-DuBu, pull requests merged in 2025-01, with the labels that each got.

#2 [INIT] 프로젝트 세팅
  frontend/.gitignore
  frontend/.husky/pre-commit
  frontend/.husky/prepare-commit-msg
  frontend/.prettierrc
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/mockServiceWorker.js
  frontend/public/vite.svg
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/main.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/.gitkeep
  frontend/src/mocks/handler/.gitkeep
  frontend/src/router/index.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: init, FE

#4 [INIT] typography 및 폰트 & 아이콘 & 화면 최소 너비 설정
  frontend/index.html
  frontend/public/favicon.ico
  frontend/src/App.tsx
  frontend/src/assets/fonts/Pretendard-Bold.subset.woff2
  frontend/src/assets/fonts/Pretendard-Medium.subset.woff2
  frontend/src/assets/fonts/Pretendard-Regular.subset.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.subset.woff2
  frontend/src/assets/react.svg
  frontend/src/components/Icon/Icon.styled.ts
  frontend/src/components/Icon/icons/AddressHome.tsx
  frontend/src/components/Icon/icons/AddressUniv.tsx
  frontend/src/components/Icon/icons/Bus.tsx
  frontend/src/components/Icon/icons/Check.tsx
  frontend/src/components/Icon/icons/CheckCircle.tsx
  frontend/src/components/Icon/icons/Chevron.tsx
  frontend/src/components/Icon/icons/Close.tsx
  frontend/src/components/Icon/icons/Edit.tsx
  frontend/src/components/Icon/icons/EmptyCheck.tsx
  frontend/src/components/Icon/icons/English.tsx
  frontend/src/components/Icon/icons/FilledArrow.tsx
  frontend/src/components/Icon/icons/FilledCheck.tsx
  frontend/src/components/Icon/icons/Fire.tsx
  frontend/src/components/Icon/icons/Hobby.tsx
  frontend/src/components/Icon/icons/Home.tsx
  frontend/src/components/Icon/icons/Language.tsx
  frontend/src/components/Icon/icons/Map.tsx
  frontend/src/components/Icon/icons/Menu.tsx
  frontend/src/components/Icon/icons/MinusCircle.tsx
  frontend/src/components/Icon/icons/News.tsx
  frontend/src/components/Icon/icons/Others.tsx
  frontend/src/components/Icon/icons/Plus.tsx
  frontend/src/components/Icon/icons/PlusCircle.tsx
  frontend/src/components/Icon/icons/Reading.tsx
  frontend/src/components/Icon/icons/Search.tsx
  frontend/src/components/Icon/icons/Subway.tsx
  frontend/src/components/Icon/icons/Switch.tsx
  frontend/src/components/Icon/icons/index.ts
  frontend/src/components/Icon/index.tsx
  frontend/src/main.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/theme.ts
Labels: init, FE

#7 [INIT] 프로젝트 세팅
  backend/.gitattributes
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/dubu/backend/BackendApplication.java
  backend/src/main/java/com/dubu/backend/global/config/AppConfig.java
  backend/src/main/java/com/dubu/backend/global/config/OctetStreamReadMsgConverter.java
  backend/src/main/java/com/dubu/backend/global/config/P6SpyFormatter.java
  backend/src/main/java/com/dubu/backend/global/config/QueryDslConfig.java
  backend/src/main/java/com/dubu/backend/global/config/RedisConfig.java
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/global/domain/BaseTimeEntity.java
  backend/src/main/java/com/dubu/backend/global/exception/BadRequestException.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorResponse.java
  backend/src/main/java/com/dubu/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dubu/backend/global/exception/InternalServerException.java
  backend/src/main/java/com/dubu/backend/global/exception/UnauthorizedException.java
  backend/src/test/java/com/dubu/backend/BackendApplicationTests.java
Labels: init, BE

#14 [FEAT] Todo 관련 엔티티 구현
  backend/src/main/java/com/dubu/backend/todo/entity/Category.java
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoDifficulty.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoType.java
Labels: feat, BE

#17 [TEST] DB 테스트를 위한 환경 세팅
  backend/src/test/java/com/dubu/backend/config/TestP6SpySqlFormatConfig.java
  backend/src/test/java/com/dubu/backend/config/TestQueryDslConfig.java
  backend/src/test/java/com/dubu/backend/config/annotation/CustomDataJpaTest.java
Labels: test, BE

#19 [FEAT] 공통 헤더 컴포넌트 구현
  frontend/src/components/Header/Header.constants.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/HeaderButtons/Back.tsx
  frontend/src/components/Header/HeaderButtons/Complete.tsx
  frontend/src/components/Header/HeaderButtons/Home.tsx
  frontend/src/components/Header/HeaderButtons/Menu.tsx
  frontend/src/components/Header/HeaderButtons/Next.tsx
  frontend/src/components/Header/HeaderButtons/index.tsx
  frontend/src/components/Header/hooks/useNavigation.ts
  frontend/src/components/Header/index.tsx
Labels: feat, FE

#20 [FEAT] Tab 공통 컴포넌트 구현
  frontend/src/components/Tab/Tab.types.ts
  frontend/src/components/Tab/TabActiveIndicator.tsx
  frontend/src/components/Tab/TabContent.tsx
  frontend/src/components/Tab/TabList.tsx
  frontend/src/components/Tab/TabRoot.tsx
  frontend/src/components/Tab/TabTrigger.tsx
  frontend/src/components/Tab/index.ts
  frontend/src/contexts/TabContext.ts
  frontend/src/hooks/useTabContext.ts
  frontend/src/pages/EditPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE
