Repository softeer5th/Team6-DuBu, pull requests merged in 2025-02, with the labels that each got.

#28 [FEAT] 카카오 로그인 및 회원가입 구현
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/dubu/backend/BackendApplication.java
  backend/src/main/java/com/dubu/backend/auth/api/AuthController.java
  backend/src/main/java/com/dubu/backend/auth/api/OauthProviderConverter.java
  backend/src/main/java/com/dubu/backend/auth/application/AuthService.java
  backend/src/main/java/com/dubu/backend/auth/application/JwtManager.java
  backend/src/main/java/com/dubu/backend/auth/application/TokenService.java
  backend/src/main/java/com/dubu/backend/auth/domain/OauthProvider.java
  backend/src/main/java/com/dubu/backend/auth/domain/authcode/AuthCodeRequestUrlProvider.java
  backend/src/main/java/com/dubu/backend/auth/domain/authcode/AuthCodeRequestUrlProviderComposite.java
  backend/src/main/java/com/dubu/backend/auth/dto/TokenResponse.java
  backend/src/main/java/com/dubu/backend/auth/exception/RefreshTokenExpiredException.java
  backend/src/main/java/com/dubu/backend/auth/exception/TokenBlacklistedException.java
  backend/src/main/java/com/dubu/backend/auth/exception/TokenExpiredException.java
  backend/src/main/java/com/dubu/backend/auth/exception/TokenInvalidException.java
  backend/src/main/java/com/dubu/backend/auth/exception/TokenMissingException.java
  backend/src/main/java/com/dubu/backend/auth/exception/UnsupportedSocialLoginTypeException.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/KakaoOauthConfig.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/adapter/KakaoAuthCodeHttpClient.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/adapter/KakaoTokenHttpClient.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/adapter/KakaoUserHttpClient.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/port/KakaoTokenPort.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/port/KakaoUserPort.java
  backend/src/main/java/com/dubu/backend/auth/infra/repository/TokenRedisRepository.java
  backend/src/main/java/com/dubu/backend/global/aop/token/TokenValid.java
  backend/src/main/java/com/dubu/backend/global/aop/token/TokenValidAspect.java
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/global/domain/ErrorResponse.java
  backend/src/main/java/com/dubu/backend/global/domain/SuccessResponse.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dubu/backend/member/domain/Member.java
  backend/src/main/java/com/dubu/backend/member/domain/enums/Role.java
  backend/src/main/java/com/dubu/backend/member/domain/enums/Status.java
  backend/src/main/java/com/dubu/backend/member/infrastructure/repository/MemberRepository.java
Labels: feat, BE

#24 [FEAT] Drawer 컴포넌트 구현
  frontend/src/components/Drawer/Drawer.constants.ts
  frontend/src/components/Drawer/Drawer.styled.ts
  frontend/src/components/Drawer/contexts/DrawerContext.tsx
  frontend/src/components/Drawer/contexts/DrawerProvider.tsx
  frontend/src/components/Drawer/hooks/useDrawer.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/HeaderButtons/Menu.tsx
  frontend/src/components/Header/index.tsx
Labels: feat, FE

#30 [FEAT] 할 일 수정하기 UI 퍼블리싱 & 날짜 정보 query parameter로 관리
  frontend/src/api/todo.ts
  frontend/src/components/Button/IconButton/IconButton.styled.ts
  frontend/src/components/Button/IconButton/index.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useQueryParamsDate.ts
  frontend/src/hooks/useTodoListQuery.ts
  frontend/src/mocks/data/favoriteTodo.json
  frontend/src/mocks/data/recommendTodo.json
  frontend/src/mocks/data/todayTodo.json
  frontend/src/mocks/data/tomorrowTodo.json
  frontend/src/mocks/handlers/todo.ts
  frontend/src/pages/EditPage/EditPage.constants.ts
  frontend/src/pages/EditPage/EditPage.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/FavoriteTab.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/RecommendTab.styled.ts
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoEditItem/TodoEditItem.styled.ts
  frontend/src/pages/EditPage/components/TodoEditItem/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/TodoTab.styled.ts
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useFavoriteListQuery.ts
  frontend/src/pages/EditPage/hooks/useRecommendListQuery.ts
  frontend/src/pages/EditPage/index.tsx
  frontend/src/pages/MainPage/components/DateHeader/index.tsx
  frontend/src/pages/MainPage/components/TodoListContainer/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/category.ts
Labels: feat, design, FE

#33 [FEAT] 사용자 온보딩 기능 구현
  backend/src/main/java/com/dubu/backend/auth/api/AuthController.java
  backend/src/main/java/com/dubu/backend/auth/application/AuthService.java
  backend/src/main/java/com/dubu/backend/auth/application/TokenService.java
  backend/src/main/java/com/dubu/backend/global/aop/token/TokenValid.java
  backend/src/main/java/com/dubu/backend/global/aop/token/TokenValidAspect.java
  backend/src/main/java/com/dubu/backend/global/config/OpenApiConfig.java
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/NotFoundException.java
  backend/src/main/java/com/dubu/backend/global/interceptor/TokenInterceptor.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/member/domain/Address.java
  backend/src/main/java/com/dubu/backend/member/domain/Member.java
  backend/src/main/java/com/dubu/backend/member/domain/MemberCategory.java
  backend/src/main/java/com/dubu/backend/member/domain/enums/AddressType.java
  backend/src/main/java/com/dubu/backend/member/domain/enums/Status.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberOnboardingRequest.java
  backend/src/main/java/com/dubu/backend/member/exception/MemberNotFoundException.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/AddressRepository.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/MemberCategoryRepository.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/MemberRepository.java
  backend/src/main/java/com/dubu/backend/todo/exception/CategoryNotFoundException.java
  backend/src/main/java/com/dubu/backend/todo/infra/repository/CategoryRepository.java
Labels: feat, BE

#34 [FEAT] BottomSheet 공통 컴포넌트 구현
  frontend/src/components/BottomSheet/BottomSheet.styled.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useFavoriteListQuery.ts
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/theme.ts
Labels: feat, design, FE

#37 [FEAT] 온보딩 페이지 UI 퍼블리싱
  frontend/src/assets/images/backgroundEnglish.png
  frontend/src/assets/images/backgroundHobby.png
  frontend/src/assets/images/backgroundLanguage.png
  frontend/src/assets/images/backgroundNews.png
  frontend/src/assets/images/backgroundReading.png
  frontend/src/components/Header/HeaderButtons/Back.tsx
  frontend/src/components/Icon/icons/AddressHome.tsx
  frontend/src/components/Icon/icons/AddressUniv.tsx
  frontend/src/components/Icon/icons/Alert.tsx
  frontend/src/components/Icon/icons/index.ts
  frontend/src/pages/OnboardingPage/OnboardingPage.constants.ts
  frontend/src/pages/OnboardingPage/OnboardingPage.types.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingHeader/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingPageContent.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingProgress/OnboardingProgress.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingProgress/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/StepDescription/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/StepGuide/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step1/Step1.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step1/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/Step2.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step3/Step3.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step3/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/index.tsx
  frontend/src/pages/OnboardingPage/contexts/OnboardingContext.tsx
  frontend/src/pages/OnboardingPage/contexts/OnboardingProvider.tsx
  frontend/src/pages/OnboardingPage/hooks/useOnboarding.ts
  frontend/src/pages/OnboardingPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#38 [FEAT] 주소 검색 기능 구현
  backend/src/main/java/com/dubu/backend/global/domain/ErrorResponse.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dubu/backend/global/exception/ServiceUnavailableException.java
  backend/src/main/java/com/dubu/backend/member/api/PlaceController.java
  backend/src/main/java/com/dubu/backend/member/application/PlaceService.java
  backend/src/main/java/com/dubu/backend/member/dto/NaverPlaceApiResponse.java
  backend/src/main/java/com/dubu/backend/member/dto/SearchPlaceResponse.java
  backend/src/main/java/com/dubu/backend/member/exception/NaverApiServerException.java
  backend/src/main/java/com/dubu/backend/member/infra/place/NaverApiConfig.java
  backend/src/main/java/com/dubu/backend/member/infra/place/NaverPlaceApiClient.java
Labels: feat, BE

#40 [FEAT] 사용자 상태 및 출도착지 조회 기능 구현
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberSavedAddressResponse.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberStatusResponse.java
  backend/src/main/java/com/dubu/backend/member/exception/MemberSavedAddressNotFoundException.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/AddressRepository.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/MemberRepository.java
Labels: feat, BE

#36 FEAT] Todo 생성, 수정, 삭제 API 구현
  backend/src/main/java/com/dubu/backend/global/domain/ErrorResponse.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/member/exception/NotFoundMemberException.java
  backend/src/main/java/com/dubu/backend/todo/controller/TodoController.java
  backend/src/main/java/com/dubu/backend/todo/dto/request/CreateTodoFromArchivedRequest.java
  backend/src/main/java/com/dubu/backend/todo/dto/request/CreateTodoRequest.java
  backend/src/main/java/com/dubu/backend/todo/dto/request/UpdateTodoRequest.java
  backend/src/main/java/com/dubu/backend/todo/dto/response/TodoInfo.java
  backend/src/main/java/com/dubu/backend/todo/entity/Category.java
  backend/src/main/java/com/dubu/backend/todo/entity/Schedule.java
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoDifficulty.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoType.java
  backend/src/main/java/com/dubu/backend/todo/exception/AlreadyAddedTodoFromArchivedException.java
  backend/src/main/java/com/dubu/backend/todo/exception/ScheduleNotFoundException.java
  backend/src/main/java/com/dubu/backend/todo/exception/TodoLimitExceededException.java
  backend/src/main/java/com/dubu/backend/todo/exception/TodoNotFoundException.java
  backend/src/main/java/com/dubu/backend/todo/repository/CategoryRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomScheduleRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomScheduleRepositoryImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/ScheduleRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/service/TodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodoManagementServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/service/resolver/ScheduledDateResolver.java
  backend/src/test/java/com/dubu/backend/todo/service/impl/TodoCreateFromArchivedTest.java
  backend/src/test/java/com/dubu/backend/todo/service/impl/TodoCreateTest.java
Labels: feat, BE

#43 [FEAT] BottomSheet UI 퍼블리싱 및 API 연동
  frontend/src/api/fetchClient.ts
  frontend/src/api/todo.ts
  frontend/src/components/BottomSheet/BottomSheet.styled.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/components/RadioGroup/RadioGroup.styled.ts
  frontend/src/components/RadioGroup/index.tsx
  frontend/src/components/Tab/Tab.types.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useTodoListQuery.ts
  frontend/src/mocks/data/favoriteTodo.json
  frontend/src/mocks/data/recommendTodo.json
  frontend/src/mocks/data/todayTodo.json
  frontend/src/mocks/data/todoData.json
  frontend/src/mocks/data/tomorrowTodo.json
  frontend/src/mocks/handlers/todo.ts
  frontend/src/pages/EditPage/EditPage.constants.ts
  frontend/src/pages/EditPage/EditPage.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/FavoriteTab.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/RecommendTab.styled.ts
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoEditForm/TodoEditForm.styled.ts
  frontend/src/pages/EditPage/components/TodoEditForm/index.tsx
  frontend/src/pages/EditPage/components/TodoEditItem/TodoEditItem.styled.ts
  frontend/src/pages/EditPage/components/TodoEditItem/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/TodoAddForm/TodoAddForm.styled.ts
  frontend/src/pages/EditPage/components/TodoTab/TodoAddForm/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/TodoTab.styled.ts
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useBaseBottomSheet.ts
  frontend/src/pages/EditPage/hooks/useDeleteTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useEditTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useEditTodoMutation.ts
  frontend/src/pages/EditPage/index.tsx
  frontend/src/pages/MainPage/components/TodoListContainer/index.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/category.ts
  frontend/src/types/filter.ts
  frontend/src/types/todo.ts
Labels: feat, design, FE

#50 [FEAT] 모든 추천 UI 퍼블리싱 및 추천 할 일 필터링 로직 구현
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/api/todo.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/components/Button/IconButton/IconButton.styled.ts
  frontend/src/components/Button/IconButton/index.tsx
  frontend/src/components/RadioGroup/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/recommendTodo.json
  frontend/src/mocks/handlers/todo.ts
  frontend/src/pages/EditPage/EditPage.constants.ts
  frontend/src/pages/EditPage/EditPage.styled.ts
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoEditForm/index.tsx
  frontend/src/pages/EditPage/hooks/useRecommendListQuery.ts
  frontend/src/pages/EditPage/index.tsx
  frontend/src/pages/RecommendTodoPage/RecommendTodoPage.utils.ts
  frontend/src/pages/RecommendTodoPage/components/FilterForm/FilterForm.styled.ts
  frontend/src/pages/RecommendTodoPage/components/FilterForm/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/RecommendTodoContainer.styled.ts
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RecommendTodoPage/hooks/useFilterBottomSheet.tsx
  frontend/src/pages/RecommendTodoPage/hooks/useRecommendTodoFilterQuery.ts
  frontend/src/pages/RecommendTodoPage/index.tsx
  frontend/src/router/index.tsx
  frontend/src/router/layout/FlexPageLayout.tsx
Labels: feat, design, FE

#49 [FEAT] 출도착지를 통한 대중교통 경로 조회 기능 구현
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/member/api/PlaceController.java
  backend/src/main/java/com/dubu/backend/member/application/PlaceService.java
  backend/src/main/java/com/dubu/backend/member/dto/PlaceSearchResponse.java
  backend/src/main/java/com/dubu/backend/member/infra/client/NaverApiConfig.java
  backend/src/main/java/com/dubu/backend/member/infra/client/NaverPlaceApiClient.java
  backend/src/main/java/com/dubu/backend/plan/api/RouteController.java
  backend/src/main/java/com/dubu/backend/plan/application/RouteService.java
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Plan.java
  backend/src/main/java/com/dubu/backend/plan/domain/enums/CongestionLevel.java
  backend/src/main/java/com/dubu/backend/plan/domain/enums/TrafficType.java
  backend/src/main/java/com/dubu/backend/plan/domain/vo/PathIdentifier.java
  backend/src/main/java/com/dubu/backend/plan/dto/OdsayRouteApiResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/RouteSearchResponseDto.java
  backend/src/main/java/com/dubu/backend/plan/infra/client/OdsayApiClient.java
  backend/src/main/java/com/dubu/backend/plan/infra/client/OdsayApiConfig.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PathRepository.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
Labels: feat, BE

#48 [FEAT] 즐겨찾기 조회 API 구현
  backend/src/main/java/com/dubu/backend/global/domain/PageResponse.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/member/exception/MemberCategoryNotFoundException.java
  backend/src/main/java/com/dubu/backend/member/exception/NotFoundMemberException.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/MemberCategoryRepository.java
  backend/src/main/java/com/dubu/backend/todo/controller/TodoController.java
  backend/src/main/java/com/dubu/backend/todo/dto/request/SaveTodoQueryRequest.java
  backend/src/main/java/com/dubu/backend/todo/dto/response/TodoInfo.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoType.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomScheduleRepositoryImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepositoryImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/service/TodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodoManagementServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodoQueryServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/support/ScheduledDateResolver.java
  backend/src/main/java/com/dubu/backend/todo/support/TodoRandomSelector.java
  backend/src/test/java/com/dubu/backend/todo/service/impl/TodoCreateTest.java
  backend/src/test/java/com/dubu/backend/todo/support/RandomPerformanceTest.java
Labels: feat, BE

#54 [FEAT] 주소 검색 기능 및 온보딩 정보 등록 기능 구현
  frontend/src/api/fetchClient.ts
  frontend/src/api/onboarding.ts
  frontend/src/api/search.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/SearchAddress/SearchAddress.styled.ts
  frontend/src/components/SearchAddress/SearchAddressHeader/index.tsx
  frontend/src/components/SearchAddress/SearchAddressResult/SearchAddressResult.styled.ts
  frontend/src/components/SearchAddress/SearchAddressResult/index.tsx
  frontend/src/components/SearchAddress/SearchAddressSearchBar/SearchAddressSearchBar.styled.ts
  frontend/src/components/SearchAddress/SearchAddressSearchBar/index.tsx
  frontend/src/components/SearchAddress/hooks/useSearchAddressQuery.ts
  frontend/src/components/SearchAddress/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/address.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/onboarding.ts
  frontend/src/mocks/handlers/search.ts
  frontend/src/pages/OnboardingPage/OnboardingPage.constants.ts
  frontend/src/pages/OnboardingPage/OnboardingPage.types.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingHeader/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingPageContent.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/StepDescription/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step1/Step1.constants.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step1/Step1.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step1/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/SearchAddressButton/SearchAddressButton.constants.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/SearchAddressButton/SearchAddressButton.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/SearchAddressButton/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/Step2.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step3/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/index.tsx
  frontend/src/pages/OnboardingPage/contexts/OnboardingProvider.tsx
  frontend/src/pages/OnboardingPage/hooks/useStepValidity.ts
Labels: feat, FE

#45 [FEAT] 오늘 할 일 리스트, 내일 할 일 리스트 조회 API 구현
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
Labels: feat, BE

#58 [FEAT] 선택한 경로로 출발하기 및 이동 중 관련 기능 구현
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/interceptor/TokenInterceptor.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanController.java
  backend/src/main/java/com/dubu/backend/plan/api/RouteController.java
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/application/RouteService.java
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Plan.java
  backend/src/main/java/com/dubu/backend/plan/domain/enums/CongestionLevel.java
  backend/src/main/java/com/dubu/backend/plan/domain/enums/TrafficType.java
  backend/src/main/java/com/dubu/backend/plan/dto/request/PlanSaveRequest.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/OdsayRouteApiResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/PlanRecentResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/RouteSearchResponse.java
  backend/src/main/java/com/dubu/backend/plan/exception/InvalidMemberStatusException.java
  backend/src/main/java/com/dubu/backend/plan/exception/InvalidTrafficTypeException.java
  backend/src/main/java/com/dubu/backend/plan/exception/NotFoundPlanException.java
  backend/src/main/java/com/dubu/backend/plan/exception/UnauthorizedPlanDeletionException.java
  backend/src/main/java/com/dubu/backend/plan/infra/client/OdsayApiClient.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/CustomPathRepository.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/CustomPathRepositoryImpl.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PathRepository.java
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoType.java
Labels: feat, BE

#56 [FEAT] 경로별 할 일 수정 UI 퍼블리싱 및 msw 연동
  frontend/src/api/todo.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/HeaderButtons/Back.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useQueryParamsDate.ts
  frontend/src/hooks/useRouteTodoQuery.ts
  frontend/src/hooks/useTodoListQuery.ts
  frontend/src/mocks/data/archivedTodo.json
  frontend/src/mocks/data/routeTodo.json
  frontend/src/mocks/handlers/todo.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/TodoAddForm/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/TodoTab.styled.ts
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useDeleteTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useEditTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useEditTodoMutation.ts
  frontend/src/pages/EditPage/index.tsx
  frontend/src/pages/MainPage/MainPage.styled.ts
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RouteTodoEditPage/RouteTodoEditPage.styled.ts
  frontend/src/pages/RouteTodoEditPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, design, FE

#64 [FEAT] 이동중 페이지 UI 퍼블리싱 및 msw 연동
  frontend/src/api/plan.ts
  frontend/src/api/todo.ts
  frontend/src/components/Icon/icons/EmptyCheck.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useRouteTodoQuery.ts
  frontend/src/hooks/useTodoListQuery.ts
  frontend/src/mocks/data/planInfo.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/plan.ts
  frontend/src/mocks/handlers/todo.ts
  frontend/src/pages/EditPage/EditPage.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useDeleteTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useEditTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useEditTodoMutation.ts
  frontend/src/pages/MainPage/MainPage.utils.ts
  frontend/src/pages/MainPage/components/DateHeader/index.tsx
  frontend/src/pages/PlanPage/PlanPage.constants.ts
  frontend/src/pages/PlanPage/PlanPage.styled.ts
  frontend/src/pages/PlanPage/PlanPage.types.ts
  frontend/src/pages/PlanPage/PlanPage.utils.ts
  frontend/src/pages/PlanPage/components/PlanHeader/index.tsx
  frontend/src/pages/PlanPage/components/PlanInfoHeader/PlanInfoHeader.styled.ts
  frontend/src/pages/PlanPage/components/PlanInfoHeader/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockContent.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/TimeBlockList.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockHeader/TimeBlockHeader.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockHeader/index.tsx
  frontend/src/pages/PlanPage/hooks/usePlanInfoQuery.ts
  frontend/src/pages/PlanPage/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RouteTodoEditPage/index.tsx
  frontend/src/router/index.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/utils/time.ts
Labels: feat, design, FE

#72 [FEAT] GitHub Actions workflow 및 applicaiton-prod.yaml 파일 작성
  .github/workflows/deploy.yml
  .gitignore
  backend/src/main/resources/application-prod.yaml
Labels: feat, BE

#63 [FEAT] 경로 선택 페이지 UI 퍼블리싱 및 경로 조회 기능 구현
  frontend/src/api/search.ts
  frontend/src/components/Icon/icons/Subway.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/subwayLines.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/routes.json
  frontend/src/mocks/handlers/search.ts
  frontend/src/pages/RouteSelectPage/RouteSelectPage.styled.ts
  frontend/src/pages/RouteSelectPage/RouteSelectPage.types.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteBar/RouteBar.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteBar/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteDetail/RouteDetail.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteDetail/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteItem.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteItem.utils.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteTimeInfo/RouteTimeInfo.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteTimeInfo/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteList.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteResult.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/StartTime/StartTime.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/StartTime/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/RouteSelectAddress/RouteSelectAddress.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/RouteSelectAddress/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/RouteSelectHeader/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/RouteSelectTop.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/index.tsx
  frontend/src/pages/RouteSelectPage/hooks/useSearchRoutesQuery.ts
  frontend/src/pages/RouteSelectPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#62 [FEAT] 할 일 수정하기 단계의 할 일 추천 기능 구현
  backend/src/main/java/com/dubu/backend/todo/controller/TodoController.java
  backend/src/main/java/com/dubu/backend/todo/repository/ScheduleRepository.java
Labels: feat, BE

#73 [FEAT] Context API를 활용하여 Toast UI 사용성 개선하기
  frontend/src/components/Button/IconButton/IconButton.styled.ts
  frontend/src/components/Toast/Toast.styled.ts
  frontend/src/components/Toast/ToastProvider.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/message.ts
  frontend/src/contexts/ToastContext.ts
  frontend/src/hooks/useToast.ts
  frontend/src/main.tsx
  frontend/src/pages/EditPage/EditPage.constants.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useEditTodoBottomSheet.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RouteTodoEditPage/RouteTodoEditPage.styled.ts
  frontend/src/styles/GlobalStyle.tsx
Labels: feat, refactor, FE

#69 [FEAT] 이동 중료 후 사용자 상태 변경 및 피드백 작성 기능 구현
  backend/src/main/java/com/dubu/backend/global/config/SchedulerConfig.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/api/PlaceController.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/member/application/PlaceService.java
  backend/src/main/java/com/dubu/backend/member/domain/enums/Status.java
  backend/src/main/java/com/dubu/backend/member/dto/request/MemberOnboardingRequest.java
  backend/src/main/java/com/dubu/backend/member/dto/request/MemberStatusUpdateRequest.java
  backend/src/main/java/com/dubu/backend/member/dto/response/MemberSavedAddressResponse.java
  backend/src/main/java/com/dubu/backend/member/dto/response/MemberStatusResponse.java
  backend/src/main/java/com/dubu/backend/member/dto/response/NaverPlaceApiResponse.java
  backend/src/main/java/com/dubu/backend/member/dto/response/PlaceSearchResponse.java
  backend/src/main/java/com/dubu/backend/member/exception/InvalidStatusException.java
  backend/src/main/java/com/dubu/backend/member/infra/client/NaverPlaceApiClient.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanController.java
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/application/TaskSchedulerService.java
  backend/src/main/java/com/dubu/backend/plan/domain/Feedback.java
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Plan.java
  backend/src/main/java/com/dubu/backend/plan/domain/enums/Mood.java
  backend/src/main/java/com/dubu/backend/plan/dto/request/PlanCreateRequest.java
  backend/src/main/java/com/dubu/backend/plan/dto/request/PlanFeedbackCreateRequest.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/FeedbackWritePageInfoResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/PlanRecentResponse.java
  backend/src/main/java/com/dubu/backend/plan/exception/InvalidMoodException.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/FeedbackRepository.java
  backend/src/main/java/com/dubu/backend/todo/entity/Category.java
Labels: feat, BE

#81 [FEAT] 인증, 회원, 계획 관련 Swagger 명세 작성
  backend/src/main/java/com/dubu/backend/auth/api/AuthApi.java
  backend/src/main/java/com/dubu/backend/auth/api/AuthController.java
  backend/src/main/java/com/dubu/backend/member/api/MemberApi.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/api/PlaceApi.java
  backend/src/main/java/com/dubu/backend/member/api/PlaceController.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanApi.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanController.java
  backend/src/main/java/com/dubu/backend/plan/api/RouteApi.java
  backend/src/main/java/com/dubu/backend/plan/api/RouteController.java
  backend/src/main/java/com/dubu/backend/todo/entity/Schedule.java
Labels: feat, BE

#78 [FEAT] 메인화면-이동전 페이지 세부 기능 구현
  frontend/eslint.config.js
  frontend/src/api/member.ts
  frontend/src/api/onboarding.ts
  frontend/src/api/search.ts
  frontend/src/components/Icon/icons/Plus.tsx
  frontend/src/components/SearchAddress/SearchAddress.styled.ts
  frontend/src/components/SearchAddress/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/memberAddress.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/member.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/MainPage/MainPage.utils.ts
  frontend/src/pages/MainPage/components/DateHeader/index.tsx
  frontend/src/pages/MainPage/components/RouteSection/RouteItem/RouteItem.styled.ts
  frontend/src/pages/MainPage/components/RouteSection/RouteItem/index.tsx
  frontend/src/pages/MainPage/components/RouteSection/RouteSection.styled.ts
  frontend/src/pages/MainPage/components/RouteSection/index.tsx
  frontend/src/pages/MainPage/components/StartButton/StartButton.styled.ts
  frontend/src/pages/MainPage/components/StartButton/index.tsx
  frontend/src/pages/MainPage/components/TodoListContainer/TodoListContainer.styled.ts
  frontend/src/pages/MainPage/components/TodoListContainer/index.tsx
  frontend/src/pages/MainPage/hooks/useMemberAddressQuery.ts
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RouteSelectPage/RouteSelectPage.utils.ts
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/RouteSelectAddress/RouteSelectAddress.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteSelectTop/RouteSelectAddress/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#59 [FIX] 할 일 생성, 수정, 삭제 기능 수정
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/todo/dto/enums/TodoRequestType.java
  backend/src/main/java/com/dubu/backend/todo/exception/InvalidTodoRequestTypeException.java
  backend/src/main/java/com/dubu/backend/todo/repository/ScheduleRepository.java
Labels: fix, BE

#93 [REFACTOR] 할 일 관련 기능 1차 리팩토링
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/todo/controller/TodoController.java
  backend/src/main/java/com/dubu/backend/todo/dto/response/TodoManageResult.java
  backend/src/main/java/com/dubu/backend/todo/dto/response/TodoSuccessResponse.java
  backend/src/main/java/com/dubu/backend/todo/exception/TodoTypeMismatchException.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/PathTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/PathTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/SaveTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/SaveTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TomorrowTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TomorrowTodoQueryService.java
Labels: refactor, BE

#97 [FEAT] 카카오 로그인 API 연동
  frontend/src/api/fetchClient.ts
  frontend/src/api/login.ts
  frontend/src/constants/url.ts
  frontend/src/pages/KakaoLoginPage/hooks/useKakaoLoginMutation.tsx
  frontend/src/pages/KakaoLoginPage/index.tsx
  frontend/src/pages/LandingPage/components/KakaoLoginButton/index.tsx
  frontend/src/router/index.tsx
  frontend/src/types/auth.ts
Labels: feat, FE

#94 [FEAT] 피드백 페이지 UI 퍼블리싱
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/api/feedback.ts
  frontend/src/assets/animations/feedbackAnimation.json
  frontend/src/assets/images/backgroundFeedback.png
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/todayAchievementData.json
  frontend/src/mocks/handlers/feedback.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/FeedbackPage/FeedbackPage.types.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackPageContent.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/FeedbackAnimation/FeedbackAnimation.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/FeedbackAnimation/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/FeedbackStep1.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Header/FeedbackStep2Header.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Header/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/AchievementDetail.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementSummary/AchievementSummary.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementSummary/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/FeedbackMemo/FeedbackMemo.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/FeedbackMemo/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/FeedbackStep2Main.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/index.tsx
  frontend/src/pages/FeedbackPage/contexts/FeedbackContext.tsx
  frontend/src/pages/FeedbackPage/contexts/FeedbackProvider.tsx
  frontend/src/pages/FeedbackPage/hooks/useAchievementQuery.ts
  frontend/src/pages/FeedbackPage/hooks/useFeedback.ts
  frontend/src/pages/FeedbackPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#106 [REFACTOR] 로그인 토큰 관리 로직 변경
  backend/build.gradle
  backend/src/main/java/com/dubu/backend/auth/api/AuthApi.java
  backend/src/main/java/com/dubu/backend/auth/api/AuthController.java
  backend/src/main/java/com/dubu/backend/auth/application/AuthService.java
  backend/src/main/java/com/dubu/backend/auth/application/JwtManager.java
  backend/src/main/java/com/dubu/backend/auth/application/TokenService.java
  backend/src/main/java/com/dubu/backend/auth/dto/AccessTokenResponse.java
  backend/src/main/java/com/dubu/backend/auth/dto/TokenResponse.java
  backend/src/main/java/com/dubu/backend/auth/exception/InvalidTokenHeaderException.java
  backend/src/main/java/com/dubu/backend/auth/exception/MissingTokenInCookieException.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/adapter/KakaoUserHttpClient.java
  backend/src/main/java/com/dubu/backend/auth/infra/repository/TokenRedisRepository.java
  backend/src/main/java/com/dubu/backend/global/config/RedisConfig.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
Labels: refactor, BE

#110 [FEAT] 대쉬보드 기능 api 에 대한 스웨거 설정
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Plan.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticApi.java
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticController.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/CategoryTodoInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/DayStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/WeekStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/service/StatisticService.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/CategoryTodoStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/DateUsageTimeStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: docs, feat, BE

#107 [FEAT] 대시보드 기능 구현
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Plan.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticController.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/CategoryTodoInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/DayStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/WeekStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/service/StatisticService.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/CategoryTodoStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/DateUsageTimeStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: feat, BE

#112 [FEAT] 이동 중 일 때 Todo 에 대한 완료 체크 기능 구현
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/todo/controller/TodoApi.java
  backend/src/main/java/com/dubu/backend/todo/controller/TodoController.java
  backend/src/main/java/com/dubu/backend/todo/dto/request/TodoCompletionToggleRequest.java
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
  backend/src/main/java/com/dubu/backend/todo/exception/TodoNotFoundException.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/PathTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/SaveTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TomorrowTodoManagementService.java
Labels: feat, BE

#115 [FIX] 이동 완료시 할 일 시간처리 로직 및 피드백 시 완료한 할 일 보여주도록 수정
  backend/src/main/java/com/dubu/backend/member/api/MemberApi.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanApi.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanController.java
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/FeedbackWritePageInfoResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/PlanRecentResponse.java
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
Labels: fix, BE

#116 [FIX] 실서버 API 연동
  frontend/src/api/feedback.ts
  frontend/src/api/fetchClient.ts
  frontend/src/api/plan.ts
  frontend/src/components/SearchAddress/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useMemberStatusQuery.ts
  frontend/src/hooks/useRedirectByMemberStatus.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/index.tsx
  frontend/src/pages/FeedbackPage/hooks/useSaveFeedbackMutation.ts
  frontend/src/pages/FeedbackPage/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/SearchAddressButton/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/index.tsx
  frontend/src/pages/OnboardingPage/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/index.tsx
  frontend/src/pages/RouteSelectPage/hooks/useCreatePlanMutation.ts
  frontend/tsconfig.json
Labels: fix, FE

#121 [FIX] 해당경로로 출발하기 API 로직 수정
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/todo/repository/ScheduleRepository.java
Labels: fix, BE

#125 [FIX] 버그데이 QA 반영
  frontend/src/api/todo.ts
  frontend/src/components/Button/IconButton/index.tsx
  frontend/src/components/SearchAddress/index.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useQueryParamsDate.ts
  frontend/src/hooks/useRouteTodoQuery.ts
  frontend/src/hooks/useTodoListQuery.ts
  frontend/src/pages/EditPage/EditPage.constants.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoEditItem/TodoEditItem.styled.ts
  frontend/src/pages/EditPage/components/TodoEditItem/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useDeleteTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useEditTodoBottomSheet.tsx
  frontend/src/pages/EditPage/hooks/useEditTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useFavoriteListQuery.ts
  frontend/src/pages/EditPage/hooks/useRecommendListQuery.ts
  frontend/src/pages/EditPage/index.tsx
  frontend/src/pages/MainPage/components/TodoListContainer/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RecommendTodoPage/hooks/useRecommendTodoFilterQuery.ts
  frontend/src/pages/RouteTodoEditPage/index.tsx
  frontend/src/types/todo.ts
Labels: fix, FE

#129 [FIX] 통계 기능 관련 버그 수정
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticApi.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/CategoryTodoInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/DayStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/WeekStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/CategoryTodoStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/DateUsageTimeStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: fix, BE

#132 [FIX] 통계 기능 추가 버그 수정
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PathRepository.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: fix, BE

#135 [FEAT] PWA 세팅
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/icons/192x192.png
  frontend/public/icons/320x320.png
  frontend/public/icons/32x32.png
  frontend/public/icons/512x512.png
  frontend/public/icons/96x96.png
  frontend/public/icons/apple-touch-icon.png
  frontend/public/netlify.toml
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: feat, FE

#136 [FEAT] 사용자 실시간 위치 정보 수집 기능 구현
  backend/src/main/java/com/dubu/backend/auth/infra/repository/TokenRedisRepository.java
  backend/src/main/java/com/dubu/backend/global/anotation/Polling.java
  backend/src/main/java/com/dubu/backend/global/domain/ErrorResponse.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dubu/backend/global/exception/InternalServerException.java
  backend/src/main/java/com/dubu/backend/member/api/MemberApi.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberLocation.java
  backend/src/main/java/com/dubu/backend/member/exception/RedisUnavailableException.java
Labels: feat, BE

#140 [REFACTOR] vitest 테스트 환경 세팅
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/mocks/data/todoData.json
  frontend/src/mocks/handlers/todo.ts
  frontend/src/mocks/server.ts
  frontend/src/pages/EditPage/components/TodoTab/TodoTab.test.tsx
  frontend/src/pages/MainPage/MainPage.test.ts
  frontend/src/tests/setup.ts
  frontend/src/tests/test-utils.tsx
  frontend/vite.config.ts
Labels: test, FE

#131 [FEAT] 주간 통계 페이지 UI 퍼블리싱 및 API 연동
  frontend/src/api/statistics.ts
  frontend/src/components/CategoryBadge/CategoryBadge.styled.ts
  frontend/src/components/CategoryBadge/index.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useMemberStatusQuery.ts
  frontend/src/mocks/data/weekStatistics.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/statistics.ts
  frontend/src/pages/WeekStatisticsPage/WeekStatisticsPage.styled.ts
  frontend/src/pages/WeekStatisticsPage/WeekStatisticsPage.utils.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsHeader/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekCategoryList/WeekCategoryItem/WeekCategoryItem.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekCategoryList/WeekCategoryItem/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekCategoryList/WeekCategoryList.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekCategoryList/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayItem/WeekDayItem.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayItem/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayList.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekOverview/WeekOverview.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekOverview/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekStatisticsMain.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/index.tsx
  frontend/src/pages/WeekStatisticsPage/hooks/useWeekStatisticsQuery.ts
  frontend/src/pages/WeekStatisticsPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#138 [FEAT] 일간 통계 페이지 UI 퍼블리싱 및 API 연동
  frontend/pnpm-lock.yaml
  frontend/src/api/statistics.ts
  frontend/src/components/Drawer/Drawer.constants.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/dayStatistics.json
  frontend/src/mocks/handlers/statistics.ts
  frontend/src/pages/DayStatisticsPage/DayStatisticsPage.styled.ts
  frontend/src/pages/DayStatisticsPage/DayStatisticsPage.utils.ts
  frontend/src/pages/DayStatisticsPage/components/DayCategoryAchievement/DayCategoryAchievement.styled.ts
  frontend/src/pages/DayStatisticsPage/components/DayCategoryAchievement/index.tsx
  frontend/src/pages/DayStatisticsPage/components/DayDate/DayDate.styled.ts
  frontend/src/pages/DayStatisticsPage/components/DayDate/index.tsx
  frontend/src/pages/DayStatisticsPage/components/DayFeedback/DayFeedback.styled.ts
  frontend/src/pages/DayStatisticsPage/components/DayFeedback/index.tsx
  frontend/src/pages/DayStatisticsPage/components/DayStatisticsHeader/index.tsx
  frontend/src/pages/DayStatisticsPage/components/DayTimeOverview/DayTimeOverview.styled.ts
  frontend/src/pages/DayStatisticsPage/components/DayTimeOverview/index.tsx
  frontend/src/pages/DayStatisticsPage/hooks/useDayStatisticsQuery.ts
  frontend/src/pages/DayStatisticsPage/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/TodoTab.test.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/index.tsx
  frontend/src/pages/WeekStatisticsPage/WeekStatisticsPage.types.ts
  frontend/src/pages/WeekStatisticsPage/WeekStatisticsPage.utils.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekCategoryList/WeekCategoryItem/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekCategoryList/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayItem/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#142 [FEAT] 온보딩 단계별 유효성 검사 추가
  frontend/src/api/onboarding.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingHeader/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/StepDescription/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step1/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step2/index.tsx
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step3/index.tsx
  frontend/src/pages/OnboardingPage/hooks/useOnboardingMutation.ts
  frontend/src/pages/OnboardingPage/hooks/useStepValidity.ts
Labels: fix, FE

#149 [FEAT] PWA를 통한 푸시 알림 기능 구현
  .github/workflows/deploy.yml
  backend/build.gradle
  backend/src/main/java/com/dubu/backend/auth/api/AuthController.java
  backend/src/main/java/com/dubu/backend/auth/application/TokenService.java
  backend/src/main/java/com/dubu/backend/auth/config/JwtConfig.java
  backend/src/main/java/com/dubu/backend/auth/config/KakaoOauthConfig.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/adapter/KakaoAuthCodeHttpClient.java
  backend/src/main/java/com/dubu/backend/auth/infra/oauth/kakao/adapter/KakaoTokenHttpClient.java
  backend/src/main/java/com/dubu/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/dubu/backend/global/config/TimeZoneConfig.java
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/global/exception/ServiceUnavailableException.java
  backend/src/main/java/com/dubu/backend/notification/api/NotificationApi.java
  backend/src/main/java/com/dubu/backend/notification/api/NotificationController.java
  backend/src/main/java/com/dubu/backend/notification/application/NotificationService.java
  backend/src/main/java/com/dubu/backend/notification/config/RabbitMQConfig.java
  backend/src/main/java/com/dubu/backend/notification/config/VapidKeyConfig.java
  backend/src/main/java/com/dubu/backend/notification/domain/PushSubscription.java
  backend/src/main/java/com/dubu/backend/notification/dto/PushMessageDto.java
  backend/src/main/java/com/dubu/backend/notification/dto/PushSubscriptionDto.java
  backend/src/main/java/com/dubu/backend/notification/exception/UnavailablePushServiceException.java
  backend/src/main/java/com/dubu/backend/notification/infra/amqp/PushMessageConsumer.java
  backend/src/main/java/com/dubu/backend/notification/infra/amqp/PushMessageProducer.java
  backend/src/main/java/com/dubu/backend/notification/infra/repository/PushSubscriptionRepository.java
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/config/OdsayApiConfig.java
  backend/src/main/java/com/dubu/backend/plan/infra/client/OdsayApiClient.java
  backend/src/main/resources/application-prod.yaml
Labels: feat, BE

#147 [FEAT] 주변 사용자의 위치 정보 조회 및 목표 순위 조회 기능 구현
  backend/src/main/java/com/dubu/backend/global/anotation/Polling.java
  backend/src/main/java/com/dubu/backend/global/config/WebConfig.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberLocation.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/LocationRedisRepository.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/MemberRepository.java
  backend/src/main/java/com/dubu/backend/share/controller/ShareApi.java
  backend/src/main/java/com/dubu/backend/share/controller/ShareController.java
  backend/src/main/java/com/dubu/backend/share/dto/request/SurroundingMemberQueryRequest.java
  backend/src/main/java/com/dubu/backend/share/dto/response/CategoryInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/MemberLocationInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/ShareInfo.java
  backend/src/main/java/com/dubu/backend/share/service/ShareService.java
  backend/src/main/java/com/dubu/backend/share/service/impl/ShareServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepositoryImpl.java
Labels: feat, BE

#146 [FIX] 피드백 페이지 버그 수정
  frontend/src/api/feedback.ts
  frontend/src/assets/animations/feedbackAnimation.json
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackPageContent.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/FeedbackAnimation/FeedbackAnimation.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/FeedbackAnimation/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep1/FeedbackStep1.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/FeedbackMemo/FeedbackMemo.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/FeedbackMemo/index.tsx
  frontend/src/pages/FeedbackPage/hooks/useSaveFeedbackMutation.ts
Labels: fix, FE

#153 [FEAT] 즐겨찾기 수정하기 UI 퍼블리싱 및 API 연동
  frontend/src/api/plan.ts
  frontend/src/components/Drawer/Drawer.constants.ts
  frontend/src/constants/message.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useRouteTodoQuery.ts
  frontend/src/hooks/useTodoListQuery.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useEditTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useFavoriteListQuery.ts
  frontend/src/pages/EditPage/hooks/useRecommendListQuery.ts
  frontend/src/pages/FavoritePage/FavoritePage.styled.ts
  frontend/src/pages/FavoritePage/components/FavoriteHeader/FavoriteHeader.tsx
  frontend/src/pages/FavoritePage/index.tsx
  frontend/src/pages/PlanPage/components/PlanHeader/index.tsx
  frontend/src/pages/RecommendTodoPage/RecommendTodoPage.utils.ts
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/RecommendTodoContainer.styled.ts
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RecommendTodoPage/hooks/useRecommendTodoFilterQuery.ts
  frontend/src/pages/RecommendTodoPage/index.tsx
  frontend/src/router/index.tsx
Labels: feat, design, FE

#156 [FIX] 할 일 관련 기능 수정
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/exception/PlanNotFoundException.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PathRepository.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/PathTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/SaveTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/SaveTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TomorrowTodoQueryService.java
Labels: fix, BE

#161 [FIX] 지도(공유) 페이지의 기능 수정
  backend/src/main/java/com/dubu/backend/share/controller/ShareApi.java
  backend/src/main/java/com/dubu/backend/share/controller/ShareController.java
  backend/src/main/java/com/dubu/backend/share/dto/response/CategoryInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/CategoryRankInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/MemberCategoryInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/MemberInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/ShareInfo.java
  backend/src/main/java/com/dubu/backend/share/dto/response/SurroundingMemberInfo.java
  backend/src/main/java/com/dubu/backend/share/service/collection/MemberCategoryCollection.java
  backend/src/main/java/com/dubu/backend/share/service/impl/ShareServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepositoryImpl.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/ShareTodoService.java
Labels: fix, BE

#167 [FIX] 통계 기능 수정
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PathRepository.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/PathIdDateCollection.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
Labels: fix, BE

#175 [FIX] 지도(공유) 페이지 기능 및 버그 수정
  backend/src/main/java/com/dubu/backend/member/infra/repository/LocationRedisRepository.java
  backend/src/main/java/com/dubu/backend/share/service/impl/ShareServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/ShareTodoService.java
Labels: fix, BE

#158 [FEAT] 마이페이지 UI 퍼블리싱 및 내 정보 수정 API 연동
  frontend/src/api/member.ts
  frontend/src/components/Drawer/Drawer.constants.ts
  frontend/src/components/Drawer/Drawer.styled.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Icon/icons/Chart.tsx
  frontend/src/components/Icon/icons/Pen.tsx
  frontend/src/components/Icon/icons/User.tsx
  frontend/src/components/Icon/icons/index.ts
  frontend/src/components/SearchAddress/SearchAddress.styled.ts
  frontend/src/constants/url.ts
  frontend/src/mocks/data/memberInfo.json
  frontend/src/mocks/handlers/member.ts
  frontend/src/pages/MyPage/MyPage.styled.ts
  frontend/src/pages/MyPage/MyPage.types.ts
  frontend/src/pages/MyPage/components/MyPageAccountInfo/MyPageAccountInfo.styled.ts
  frontend/src/pages/MyPage/components/MyPageAccountInfo/index.tsx
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageAddress/MyPageAddress.styled.ts
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageAddress/index.tsx
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageEditableSection.styled.ts
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageGoal/MyPageGoal.styled.ts
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageGoal/index.tsx
  frontend/src/pages/MyPage/components/MyPageEditableSection/index.tsx
  frontend/src/pages/MyPage/components/MyPageHeader/index.tsx
  frontend/src/pages/MyPage/contexts/MemberContext.tsx
  frontend/src/pages/MyPage/contexts/MemberProvider.tsx
  frontend/src/pages/MyPage/hooks/useMember.ts
  frontend/src/pages/MyPage/hooks/useMemberInfoMutation.ts
  frontend/src/pages/MyPage/hooks/useMemberInfoQuery.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekOverview/index.tsx
  frontend/src/router/index.tsx
Labels: feat, FE

#165 [REFACTOR] github actions CI 스크립트 작성
  .github/workflows/fe-ci.yml
  frontend/src/vite-env.d.ts
Labels: refactor, FE

#163 [FEAT] 커서 기반 무한스크롤 구현
  frontend/src/api/todo.ts
  frontend/src/components/IntersectionObserverScroll/IntersectionObserverScroll.tsx
  frontend/src/constants/url.ts
  frontend/src/pages/EditPage/EditPage.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/FavoriteTab.styled.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useFavoriteListQuery.ts
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/RecommendTodoContainer.styled.ts
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RecommendTodoPage/hooks/useRecommendTodoFilterQuery.ts
Labels: feat, FE

#159 [FEAT] 지도 실서버 API 연동 및 마커 카테고리별 필터링 기능 구현
  frontend/src/api/fetchClient.ts
  frontend/src/api/map.ts
  frontend/src/assets/images/marker-english.svg
  frontend/src/assets/images/marker-hobby.svg
  frontend/src/assets/images/marker-language.svg
  frontend/src/assets/images/marker-news.svg
  frontend/src/assets/images/marker-others.svg
  frontend/src/assets/images/marker-reading.svg
  frontend/src/assets/images/marker.svg
  frontend/src/components/Icon/icons/Reload.tsx
  frontend/src/components/Icon/icons/index.ts
  frontend/src/components/RadioGroup/RadioGroup.styled.ts
  frontend/src/components/RadioGroup/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useUpdateCurrentLocationMutation.ts
  frontend/src/mocks/data/nearbyUser.json
  frontend/src/mocks/handlers/map.ts
  frontend/src/mocks/handlers/todo.ts
  frontend/src/pages/MapPage/MapPage.styled.ts
  frontend/src/pages/MapPage/components/CategoryRank/CategoryRank.styled.ts
  frontend/src/pages/MapPage/components/CategoryRank/CategoryRankItem/index.tsx
  frontend/src/pages/MapPage/components/CategoryRank/index.tsx
  frontend/src/pages/MapPage/hooks/useAddFavoriteFromOther.ts
  frontend/src/pages/MapPage/hooks/useCategoryFilter.ts
  frontend/src/pages/MapPage/hooks/useCategoryFilters.ts
  frontend/src/pages/MapPage/hooks/useInitMap.ts
  frontend/src/pages/MapPage/hooks/useMarker.ts
  frontend/src/pages/MapPage/hooks/useNearbyUsersQuery.ts
  frontend/src/pages/MapPage/hooks/useUpdateCurrentLocation.ts
  frontend/src/pages/MapPage/index.tsx
  frontend/src/utils/map.ts
Labels: feat, FE

#177 [REFACTOR] 기존 회원 상태 변경 스케줄러를 메시지큐를 사용하도록 변경
  .github/workflows/deploy.yml
  backend/src/main/java/com/dubu/backend/member/api/MemberApi.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/application/MemberService.java
  backend/src/main/java/com/dubu/backend/member/config/MemberRabbitMQConfig.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberLocationDto.java
  backend/src/main/java/com/dubu/backend/member/dto/MemberStatusChangeDto.java
  backend/src/main/java/com/dubu/backend/member/infra/amqp/MemberStatusEventConsumer.java
  backend/src/main/java/com/dubu/backend/member/infra/amqp/MemberStatusEventProducer.java
  backend/src/main/java/com/dubu/backend/member/infra/repository/LocationRedisRepository.java
  backend/src/main/java/com/dubu/backend/notification/application/NotificationService.java
  backend/src/main/java/com/dubu/backend/notification/config/NotificationRabbitMQConfig.java
  backend/src/main/java/com/dubu/backend/notification/infra/amqp/PushMessageEventConsumer.java
  backend/src/main/java/com/dubu/backend/notification/infra/amqp/PushMessageEventProducer.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanApi.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanController.java
  backend/src/main/java/com/dubu/backend/plan/api/RouteApi.java
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/application/RouteService.java
  backend/src/main/java/com/dubu/backend/plan/application/TaskSchedulerService.java
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Plan.java
  backend/src/main/java/com/dubu/backend/plan/dto/request/PlanCreateRequest.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/PlanRecentResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/RouteSearchResponse.java
  backend/src/main/java/com/dubu/backend/share/service/impl/ShareServiceImpl.java
  backend/src/main/resources/application-prod.yaml
Labels: refactor, BE

#179 [FEAT] 이동 중 페이지에서 할 일이 속한 경로를 수정하는 기능 구현
  backend/src/main/java/com/dubu/backend/todo/controller/TodoApi.java
  backend/src/main/java/com/dubu/backend/todo/controller/TodoController.java
  backend/src/main/java/com/dubu/backend/todo/dto/request/TodoPathUpdateRequest.java
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/PathTodoManagementService.java
Labels: feat, BE

#176 [FIX] 2차 QA 반영
  frontend/src/api/map.ts
  frontend/src/constants/message.ts
  frontend/src/constants/url.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoBottomSheet.tsx
  frontend/src/pages/MapPage/components/DetailTodo/index.tsx
  frontend/src/pages/MapPage/hooks/useCategoryFilter.ts
  frontend/src/pages/MapPage/hooks/useDeleteFavoriteFromOther.ts
  frontend/src/pages/MapPage/hooks/useInitMap.ts
  frontend/src/pages/MapPage/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockContent.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockHeader/TimeBlockHeader.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockHeader/index.tsx
  frontend/src/pages/PlanPage/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteBar/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteDetail/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteItem.utils.ts
  frontend/src/styles/GlobalStyle.tsx
Labels: fix, FE

#180 [REFACTOR] 모바일 반응형 개선
  frontend/src/assets/animations/feedbackAnimation.json
  frontend/src/components/BottomSheet/BottomSheet.styled.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/components/Drawer/Drawer.constants.ts
  frontend/src/components/Drawer/Drawer.styled.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Header/HeaderButtons/Back.tsx
  frontend/src/components/Header/HeaderButtons/Home.tsx
  frontend/src/components/Header/HeaderButtons/Menu.tsx
  frontend/src/components/SearchAddress/SearchAddress.styled.ts
  frontend/src/components/SearchAddress/SearchAddressSearchBar/SearchAddressSearchBar.styled.ts
  frontend/src/hooks/useRedirectByMemberStatus.ts
  frontend/src/pages/EditPage/components/TodoEditForm/TodoEditForm.styled.ts
  frontend/src/pages/EditPage/components/TodoTab/TodoAddForm/TodoAddForm.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/AchievementDetail.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementSummary/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/FeedbackMemo/FeedbackMemo.styled.ts
  frontend/src/pages/FeedbackPage/hooks/useSaveFeedbackMutation.ts
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageAddress/MyPageAddress.styled.ts
  frontend/src/pages/MyPage/hooks/useMemberInfoQuery.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingPageContent.styled.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/OnboardingProgress/OnboardingProgress.styled.ts
  frontend/src/providers/OverlayProvider.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: refactor, FE

#183 [FIX] 카카오 로그인 리다이렉트 수정
  frontend/src/api/login.ts
Labels: fix, FE

#190 [FIX] 통계 기능 수정
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticApi.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/MoodCountInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/WeekStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/DateAvailableTimeStatistics.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/MoodCountCollection.java
  backend/src/main/java/com/dubu/backend/statistic/service/collection/PathIdDateCollection.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: fix, BE

#192 [FIX] 지도(공유)페이지에서 카테고리 랭킹에 대한 버그 수정
  backend/src/main/java/com/dubu/backend/share/dto/response/ShareInfo.java
Labels: fix, BE

#194 [FIX] 경로 선택 페이지 버그 수정
  frontend/src/constants/busType.ts
  frontend/src/pages/OnboardingPage/components/OnboardingPageContent/Steps/Step3/Step3.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockHeader/index.tsx
  frontend/src/pages/RouteSelectPage/RouteSelectPage.types.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteBar/RouteBar.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteBar/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteDetail/RouteDetail.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteDetail/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteItem.utils.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteResult.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/index.tsx
  frontend/src/styles/theme.ts
  frontend/vite.config.ts
Labels: fix, FE

#189 [FIX] s3 + cloudfront 배포 마이그레이션 + github actions 배포 자동화 스크립트 작성 + dvh 적용
  .github/workflows/fe-cd.yml
  frontend/src/components/Drawer/Drawer.styled.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Viewport/Viewport.tsx
  frontend/src/main.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackPageContent.styled.ts
  frontend/src/pages/MainPage/MainPage.styled.ts
  frontend/src/pages/PlanPage/PlanPage.styled.ts
  frontend/src/router/layout/FlexPageLayout.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: fix, FE

#184 [FEAT] PWA 푸시 알림 기능 구현
  frontend/public/service-worker.js
  frontend/src/api/notification.ts
  frontend/src/constants/url.ts
  frontend/src/hooks/useNotificationPermission.ts
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MyPage/MyPage.styled.ts
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageGoal/MyPageGoal.styled.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/PlanPage/index.tsx
Labels: feat, FE

#200 [REFACTOR] 사용자 추천 할 일 조회 API 성능 개선
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/todo/entity/TodoDifficulty.java
  backend/src/main/java/com/dubu/backend/todo/exception/NotEnoughRecommendedTodosException.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/repository/CustomTodoRepositoryImpl.java
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/PathTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/SaveTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TomorrowTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/support/TodoRandomSelector.java
  backend/src/main/resources/application-prod.yaml
Labels: refactor, BE

#196 [FIX] 3차 QA 반영
  .github/workflows/fe-cd.yml
  frontend/index.html
  frontend/src/components/BottomSheet/BottomSheet.styled.ts
  frontend/src/hooks/useNotificationPermission.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/AchievementDetail.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/index.tsx
  frontend/src/pages/MainPage/components/StartButton/StartButton.styled.ts
  frontend/src/pages/MainPage/components/TodoListContainer/TodoListContainer.styled.ts
  frontend/src/pages/MainPage/components/TodoListContainer/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/PlanPage/PlanPage.styled.ts
  frontend/src/pages/PlanPage/components/HomeModal/HomeModal.styled.ts
  frontend/src/pages/PlanPage/components/HomeModal/index.tsx
  frontend/src/pages/PlanPage/components/PlanHeader/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/TimeBlockItem/TimeBlockItem.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockHeader/TimeBlockHeader.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockHeader/index.tsx
  frontend/src/pages/PlanPage/index.tsx
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
Labels: fix, FE

#198 [REFACTOR] 유저 상태에 따라 리다이렉트시킬 때 화면 깜박임 개선
  frontend/src/constants/queryClient.ts
  frontend/src/hooks/useRedirectByMemberStatus.ts
  frontend/src/main.tsx
  frontend/src/router/index.tsx
  frontend/src/router/memberStatusLoader.ts
Labels: refactor, FE

#203 [FIX] 주간 통계, 일간 통계 조회 시 사용자 생성 시간 데이터 포함
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticApi.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/DayStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/dto/response/WeekStatisticInfo.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: fix, BE

#206 [FIX] 통계 기능에서 한 일 유무 관계없이 계획이 있을 경우 관련 데이터 전송
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/statistic/controller/StatisticApi.java
  backend/src/main/java/com/dubu/backend/statistic/service/impl/StatisticServiceImpl.java
Labels: fix, BE

#208 [FIX] 권한에 따른 리다이렉트 시킬 페이지 수정
  frontend/src/router/index.tsx
Labels: fix, FE

#209 [REFACTOR] 경로 조회시 사용자 경험 개선을 위한 경로 표시 순서 변경 및 ODsay 장애 상황 발생 시 처리 로직 추가
  backend/src/main/java/com/dubu/backend/notification/application/NotificationService.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanApi.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanController.java
  backend/src/main/java/com/dubu/backend/plan/application/PlanService.java
  backend/src/main/java/com/dubu/backend/plan/application/RouteService.java
  backend/src/main/java/com/dubu/backend/plan/domain/Path.java
  backend/src/main/java/com/dubu/backend/plan/domain/Route.java
  backend/src/main/java/com/dubu/backend/plan/domain/enums/TrafficType.java
  backend/src/main/java/com/dubu/backend/plan/dto/request/PlanCreateRequest.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/PlanRecentResponse.java
  backend/src/main/java/com/dubu/backend/plan/dto/response/RouteSearchResponse.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/RouteRepository.java
Labels: BE

#211 [FIX] 3차 QA 우선순위 상 버그 수정
  frontend/src/api/login.ts
  frontend/src/api/plan.ts
  frontend/src/api/statistics.ts
  frontend/src/assets/images/moodDissatisfied.png
  frontend/src/assets/images/moodModerate.png
  frontend/src/assets/images/moodSatisfied.png
  frontend/src/components/SearchAddress/index.tsx
  frontend/src/constants/url.ts
  frontend/src/pages/DayStatisticsPage/components/DayDate/DayDate.styled.ts
  frontend/src/pages/DayStatisticsPage/components/DayDate/index.tsx
  frontend/src/pages/DayStatisticsPage/components/DayTimeOverview/index.tsx
  frontend/src/pages/DayStatisticsPage/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Header/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackSuccessModal/FeedbackSuccessModal.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackSuccessModal/index.tsx
  frontend/src/pages/FeedbackPage/hooks/useSaveFeedbackMutation.ts
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MyPage/components/MyPageEditableSection/MyPageAddress/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteItem.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteTimeInfo/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/index.tsx
  frontend/src/pages/RouteSelectPage/hooks/useCreatePlanMutation.ts
  frontend/src/pages/WeekStatisticsPage/WeekStatisticsPage.utils.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayItem/WeekDayItem.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayItem/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/WeekDayList.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekDayList/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekOverview/WeekOverview.styled.ts
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekOverview/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/index.tsx
Labels: fix, FE

#217 [FIX] 사용성 개선을 위한 정책 변경으로 오늘/내일 할 일관련 기능 수정
  backend/src/main/java/com/dubu/backend/todo/entity/Todo.java
  backend/src/main/java/com/dubu/backend/todo/repository/TodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TodayTodoQueryService.java
  backend/src/main/java/com/dubu/backend/todo/service/impl/TomorrowTodoManagementService.java
  backend/src/main/java/com/dubu/backend/todo/support/TodoRandomSelector.java
Labels: fix, BE

#221 [TEST] 할 일 관련 비즈니스 로직에 대한 테스트 코드 작성
  backend/src/test/java/com/dubu/backend/todo/application/impl/path/PathTodoManagementServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/path/PathTodoQueryServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/save/SaveTodoManagementServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/save/SaveTodoQueryServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/statistic/StatisticServiceImplTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/today/TodayTodoManagementServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/today/TodayTodoQueryServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/tomorrow/TomorrowTodoManagementServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/impl/tomorrow/TomorrowTodoQueryServiceTest.java
  backend/src/test/java/com/dubu/backend/todo/application/support/RandomPerformanceTest.java
Labels: test

#215 [FIX] 서비스 워커가 등록되지 않는 문제 해결
  frontend/src/main.tsx
Labels: fix, FE

#223 [FIX] 메인 페이지 알림 설정 로직 추가
  frontend/src/pages/MainPage/index.tsx
Labels: fix, FE

#224 [FIX] 지도(공유) 페이지에서 주변 사용자 할 일 조회 시 보여줄 데이터 변경
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PathRepository.java
  backend/src/main/java/com/dubu/backend/plan/infra/repository/PlanRepository.java
  backend/src/main/java/com/dubu/backend/todo/application/impl/share/ShareServiceImpl.java
  backend/src/main/java/com/dubu/backend/todo/application/impl/share/ShareTodoService.java
  backend/src/main/java/com/dubu/backend/todo/dto/response/MemberInfo.java
  backend/src/main/java/com/dubu/backend/todo/infra/repository/TodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/infra/repository/querydsl/CustomTodoRepository.java
  backend/src/main/java/com/dubu/backend/todo/infra/repository/querydsl/CustomTodoRepositoryImpl.java
Labels: fix, BE

#210 [FEAT] 드래그 앤 드롭 기능 구현
  frontend/src/api/plan.ts
  frontend/src/api/todo.ts
  frontend/src/constants/message.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/url.ts
  frontend/src/pages/MapPage/index.tsx
  frontend/src/pages/PlanPage/PlanPage.styled.ts
  frontend/src/pages/PlanPage/PlanPage.utils.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/PlanContent/PlanContent.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/PlanContent/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockContent.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/TimeBlockItem/TimeBlockItem.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/TimeBlockItem/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/TimeBlockList.styled.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/index.tsx
  frontend/src/pages/PlanPage/hooks/useUpdatePathTodoMutation.ts
  frontend/src/pages/PlanPage/index.tsx
Labels: feat, FE

#229 [FIX] 통계 조회 시 활용 가능 시간 계산 로직 수정
  backend/src/main/java/com/dubu/backend/todo/application/impl/statistic/StatisticServiceImpl.java
Labels: fix, BE

#232 [FIX] 주간 통계 조회 시 모든 Mood 타입에 대하여 데이터 제공
  backend/src/main/java/com/dubu/backend/todo/application/collection/statistic/MoodCountCollection.java
Labels: fix, BE

#236 [FIX] dynamic import 오류 해결
  frontend/src/pages/LazyPage/index.tsx
  frontend/src/router/index.tsx
Labels: fix, FE

#230 [FIX] UX 개선 및 iOS notification 에러 해결
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/service-worker.js
  frontend/src/api/notification.ts
  frontend/src/components/Drawer/Drawer.styled.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/hooks/useNotificationPermission.ts
  frontend/src/main.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/AchievementDetail.styled.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackStep2/FeedbackStep2Main/AchievementDetail/index.tsx
  frontend/src/pages/FeedbackPage/components/FeedbackSuccessModal/FeedbackSuccessModal.styled.ts
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteItem.styled.ts
  frontend/vite.config.ts
Labels: fix, FE

#238 [REFACTOR] 에러 핸들링 개선 (ErrorBoundary, 404페이지 처리, mutation 에러 처리)
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/QueryProvider.tsx
  frontend/src/api/error.ts
  frontend/src/api/fetchClient.ts
  frontend/src/components/ErrorBoundary/RootErrorBoundary.tsx
  frontend/src/components/Toast/ToastProvider.tsx
  frontend/src/constants/message.ts
  frontend/src/main.tsx
  frontend/src/pages/EditPage/components/TodoTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useDeleteTodoMutation.ts
  frontend/src/pages/ErrorPage/ErrorPage.styled.ts
  frontend/src/pages/ErrorPage/RouteErrorPage.tsx
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/pages/MapPage/hooks/useInitMap.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/PlanContent/index.tsx
  frontend/src/pages/PlanPage/hooks/useCheckTodo.ts
  frontend/src/router/index.tsx
  frontend/src/types/error.ts
Labels: refactor, FE

#240 [FIX] 주간 통계 분 단위를 시간 단위로 변경
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteList/RouteItem/RouteTimeInfo/index.tsx
  frontend/src/pages/WeekStatisticsPage/components/WeekStatisticsMain/WeekOverview/index.tsx
  frontend/src/utils/time.ts
Labels: fix, FE

#242 [FIX] 모바일 사용성 향상 UI + Custom Suspense 오류 해결
  frontend/src/components/CustomSuspense/CustomSuspense.tsx
  frontend/src/components/Toast/Toast.styled.ts
  frontend/src/constants/message.ts
  frontend/src/pages/FeedbackPage/components/FeedbackPageContent/FeedbackPageContent.styled.ts
  frontend/src/pages/MainPage/components/StartButton/StartButton.styled.ts
  frontend/src/pages/MapPage/hooks/useInitMap.ts
  frontend/src/pages/MapPage/hooks/useUpdateCurrentLocation.ts
  frontend/src/pages/MapPage/index.tsx
  frontend/src/pages/PlanPage/PlanPage.styled.ts
  frontend/src/pages/RouteSelectPage/components/RouteResult/RouteResult.styled.ts
Labels: fix, refactor, FE

#246 [FEAT] FCM 기반 푸시 알림 구현
  .github/workflows/deploy.yml
  backend/build.gradle
  backend/src/main/java/com/dubu/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/dubu/backend/notification/api/NotificationApi.java
  backend/src/main/java/com/dubu/backend/notification/api/NotificationController.java
  backend/src/main/java/com/dubu/backend/notification/application/FcmService.java
  backend/src/main/java/com/dubu/backend/notification/application/NotificationService.java
  backend/src/main/java/com/dubu/backend/notification/config/FirebaseConfig.java
  backend/src/main/java/com/dubu/backend/notification/domain/FcmToken.java
  backend/src/main/java/com/dubu/backend/notification/dto/FcmTokenDto.java
  backend/src/main/java/com/dubu/backend/notification/exception/DuplicateFcmTokenException.java
  backend/src/main/java/com/dubu/backend/notification/exception/NotFoundFcmTokenException.java
  backend/src/main/java/com/dubu/backend/notification/infra/amqp/PushMessageEventConsumer.java
  backend/src/main/java/com/dubu/backend/notification/infra/repository/FcmTokenRepository.java
  backend/src/main/resources/application-prod.yaml
Labels: feat, BE

#248 [FIX] 이동중 오늘 할일 조회 에러 해결 & 추천 할 일을 추가할 때마다 새로고침되는 문제 해결 & 드래그 앤 드롭에 의한 클릭 이벤트 방지
  frontend/src/constants/message.ts
  frontend/src/pages/EditPage/components/FavoriteTab/index.tsx
  frontend/src/pages/EditPage/components/RecommendTab/index.tsx
  frontend/src/pages/EditPage/hooks/useAddTodoFromArchivedMutation.ts
  frontend/src/pages/EditPage/hooks/useAddTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useDeleteTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useEditTodoMutation.ts
  frontend/src/pages/EditPage/hooks/useRecommendListQuery.ts
  frontend/src/pages/PlanPage/components/TimeBlockContent/PlanContent/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/TimeBlockItem/index.tsx
  frontend/src/pages/PlanPage/components/TimeBlockContent/TimeBlockList/index.tsx
  frontend/src/pages/PlanPage/hooks/useUpdatePathTodoMutation.ts
  frontend/src/pages/RecommendTodoPage/components/RecommendTodoContainer/index.tsx
Labels: FE

#244 [FIX] PWA에서 서비스 워커가 실행되지 않는 문제 해결
  .github/workflows/fe-cd.yml
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/firebase-messaging-sw.js
  frontend/src/api/notification.ts
  frontend/src/config/settingFCM.ts
  frontend/src/constants/url.ts
  frontend/src/main.tsx
  frontend/src/pages/PlanPage/PlanPage.styled.ts
  frontend/src/pages/PlanPage/components/PlanInfoHeader/PlanInfoHeader.styled.ts
  frontend/src/service-worker.js
  frontend/vite.config.ts
Labels: fix, FE
