Repository softeer5th/Team6-DuBu, pull requests merged in 2025-06, with the labels that each got.

#278 [FIX] 기획 피드백을 통한 오류 수정
  backend/src/main/java/com/dubu/backend/plan/infrastructure/RestMemberApi.java
  backend/src/main/java/com/dubu/backend/todo/domain/policy/TodoDifficultyBasedPathTimePolicy.java
Labels: fix, BE

#280 [FEAT] GTM 설정
  .github/workflows/fe-cd.yml
  frontend/index.html
Labels: feat, FE

#284 [FEAT] 로그아웃 및 회원 탈퇴 기능 구현
  backend/src/main/java/com/dubu/backend/core/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dubu/backend/core/interceptor/TokenInterceptor.java
  backend/src/main/java/com/dubu/backend/core/util/DateTimeUtils.java
  backend/src/main/java/com/dubu/backend/member/api/AddressController.java
  backend/src/main/java/com/dubu/backend/member/api/AuthController.java
  backend/src/main/java/com/dubu/backend/member/api/MemberController.java
  backend/src/main/java/com/dubu/backend/member/api/swagger/AddressSwagger.java
  backend/src/main/java/com/dubu/backend/member/api/swagger/AuthSwagger.java
  backend/src/main/java/com/dubu/backend/member/api/swagger/MemberSwagger.java
  backend/src/main/java/com/dubu/backend/member/application/AuthFacade.java
  backend/src/main/java/com/dubu/backend/member/application/TokenFacade.java
  backend/src/main/java/com/dubu/backend/member/application/TokenManager.java
  backend/src/main/java/com/dubu/backend/member/application/dto/TokenInfo.java
  backend/src/main/java/com/dubu/backend/member/domain/model/Member.java
  backend/src/main/java/com/dubu/backend/member/domain/model/OauthInfo.java
  backend/src/main/java/com/dubu/backend/member/domain/repository/MemberRepository.java
  backend/src/main/java/com/dubu/backend/member/domain/service/MemberService.java
  backend/src/main/java/com/dubu/backend/plan/api/PlanApi.java
Labels: feat, refactor
